#!/bin/bash

set -eo pipefail

main() {
  clone-repo
  build-and-test
  publish-submodule
  publish-docs
  cleanup
}

clone-repo() {
  mkdir tmp
  cd tmp

  git clone git@github.com:polytypic/rea-ml.git
  cd rea-ml
}

build-and-test() {
  CI=true script/ci
}

publish-submodule() {
  git checkout main-submodule
  git rebase main
  git push --force-with-lease
  git checkout main
}

publish-docs() {
  git checkout -b gh-pages

  rm docs/.gitignore

  cp -r _build/default/_doc/_html/* docs/

  git add docs
  git commit -m 'Built GitHub pages'
  git push -f -u origin gh-pages
}

cleanup() {
  cd ../..
  rm -rf tmp
}

main
